dist: xenial
language: java

jdk:
  - openjdk11

# disable shallow clone so SonarCloud can use SCM history to compute blame data
git:
  depth: false

# the first part of the cache phase happens
# between git checkout and before_install
cache:
  directories:
    - $HOME/.m2/repository

before_install:
  - cp ./settings.xml $HOME/.m2/settings.xml

# the default java install step does
# mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
install:
  - mvn install -DskipTests=true -B -V -Psource-quality

# addons are executed between install and script
addons:
  sonarcloud:
    organization: "pantheon-tech"
    token:
      secure: "CfWzYYn1lHAdMf8zScJ2nFu/SKN8TqHk35eo8+bGyHYbxoUTyrtn30Gb8sNgtx8tLQh8iT15xmkN8Y1iZPYJ4MjGo1IvZD1L6k9KbYePjigbiJWP+wYt8wi0Pg5Nbiximo1ooIKw2yij3bUyVaoMt25K6ciOA2ARDpTEBvgZLuhfY57+v9iLRKHB41yznKdBolXPmnQtrcDTdjDBWxEE8prlAuo55gHddb2mkhrCvgR2xS7dNP7Cm1oau9fc5/2gJBCE7Qe3oVoo5t2VZTNq7L8nYLRnf5AiU+DpbrczFwVxInDyXik1l1kH0vp9aTkI11TIm/xi/1shuUwHgqHlk/iCzssFkpJPlw6Wljm+9jWHvh3tCtjr6v8MVBC0zKt8zH90xCA5WfNEk9wY4OPoYkuk03vsD/h1eJGJWvCiBzg9FjAMa0PjspaOMZvIf14w3URRSMZEq3gvFHIuqqZNDpVRr8d5Wemhu7Q/bXPetp9zdARKZ9nVKxl1MXR/BLwvfjLHgP3tWCcuMnVgww1XMvb0GyzcexO9IXYD/4extW6orQUWwZYvkBm5FUKdSgUqfxarBJz+MSHBtXWA/GaGFMdXqsDLdQrfUq4DHQDW7NK522jRaAlghr+kuDSmtrLq7OUBjro1qXZ7/xNWZCOnUIJX99rxupwK57chahKxwug="

# splitting the build into install and test parts gives us a quicker way
# to identify what went wrong
script:
  - echo ${SONAR_KEY}
  - echo "${SONAR_KEY}"
  - echo ${SONAR_SECRET}
  - echo "${SONAR_SECRET}"
  - mvn verify -B
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then mvn sonar:sonar -Dsonar.projectKey="${SONAR_KEY}" -Dsonar.organization=vainyksi -Dsonar.host.url=https://sonarcloud.io; fi

# before_cache happens before the second part of the cache phase,
# which happens after script
before_cache:
  - rm -rf $HOME/.m2/repository/io/lighty
