dist: xenial
language: java

jdk:
  - openjdk11

# the first part of the cache phase happens
# between git checkout and before_install
cache:
  directories:
    - $HOME/.m2/repository

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "bR6gMf4uTcgpoQzd664AH0b/gnnW92ZumUN9VsPHbIzYNpfuggbXkCU4EWmof0VFokVmovyO68pwAEl77OUzT8GkI20VIAnQMiJEY7vtXzY+szmg9c0Ee+PmShUNV/uIyqeFWgC7GKxtsq76gllc1Ly7eIjvVjQmryIVY8WvqQCt9ej9o7qwyjsdeW5c/8GmhOykbxNHRVzWrSM44ojC/sRdfU/Hjv0l8OtYQxyosbYKS2788t1lwWF5Juc+1pTOgD2Dk5Gd9Erwzzlczv2qklYNij6zPekIW5iue0aAJkJnMtMzUwj2g+RK9QxE18v+6t4ClJxT7FnP11NpPvgz+HR9TpGYB3tEws0rZo/Rird2eMIotPEqnyVvijXPpHM5CykMcHlSXpNENID4cmYEwEhEHHtRdfiMnJyqtL6ApVmxO5oYcaXedLDPaEtEVhk+eW0YEhvjS1v9TClRGtgi7CcAPgqT88cRWTbg4sKUFqIQBlMUZ6z7ciYS5dl7419L8AsTbXVM6o3ojujkCMi/ZbvkZ2CtpJXQSroyRgl3OEbwY0ALfxgMC8wqlroyq8s58ahFrxnlbtXPWAzskRjTWyfGqPWYb4nZEqpeg+hDU1ZkigLn1HQLF6DtlqcstpgkORVWd4E99CYleyglj0oTWuN204VynHux5pf1x4i1lyw="

before_install:
  - cp ./settings.xml $HOME/.m2/settings.xml
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

# the default java install step does
# mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
install:
  - mvn install -DskipTests=true -B -V

# addons are executed between install and script
addons:
#  sonarcloud:
#    organization: "pantheon-tech"
#    token:
#      secure: "fkcWYUhv3v2sq2uJXu+IPhnZAQpMoytVk/GxzpYsnRVXIv1Ttm3aWWIn9NekhCRvKbSPTvggc522D/uxz1uiCTbpK4HM8Pf3pCQZkVCrAWFrTmeIuhJY4lz4JrEWzUmFH0qx/9xUrktxUESIcJsbr6BEDOtYfN3r4BhaCXkXqgfNZT2mas9gAxlLjDecauaETbSuQZydR6wkuzPLq5o7VvEyYt7jC3iNaCpSb05Nk+tdr2B36pe/O92bLasgbmCxUMY/UELE/Dk/YxMBXv4/sH1Kw45NGTqq5b0317OM8xhAylNokruw22J8k788xtXwySetGkyMsnOiu+ibtDVFbt+mlJ7p5JaMX7ZWkHP5iHgQypqm0gsLRwq2HdwZj4UramwmOPqvAl2veCzTkQ+R01nr/BjAmRxO1kVtK7/lTjHFwV527e7e2ZtvvEJEq1ukzJ25jbHDxZrrYqykMAPwgHztjiHZpQymSN7fnXSnbmo3LDsXnQwKv+z3f6J6zkh/EonxDEr3XEP+ixGCbl4M/Duq0M5Qy6Qi/j8KmhD1JQ/Hys0tl2Co9BoQ+wLRM0DqkWrWisay9ZsJKO6PB7mmo0JGbH9H1JHiuiC2CHPMxktbe+lf476Vnewe1yU/O/116QC+vPlBy0DBgNXSr4Q7BtaR6P/eUoRag06uAOk3fLw="
  coverity_scan:
    project:
      name: "vainyksi/lighty-core-coverity1"
      description: "<Your project description here>"
    notification_email: banik.michal.sk@gmail.com
    build_command: mvn clean install
    branch_pattern: coverity_scan

# splitting the build into install and test parts gives us a quicker way
# to identify what went wrong
script:
#  - mvn test -B
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then mvn clean install ; fi
#  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then mvn sonar:sonar -Dsonar.projectKey=PantheonTechnologies_lighty-core -Dsonar.host.url=https://sonarcloud.io; fi

# before_cache happens before the second part of the cache phase,
# which happens after script
before_cache:
  - rm -rf $HOME/.m2/repository/io/lighty
